# Generated by Django 4.2 on 2023-12-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GearboxType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('warranty', models.IntegerField()),
                ('year', models.IntegerField()),
                ('num_doors', models.IntegerField()),
                ('num_seats', models.IntegerField()),
                ('cc', models.IntegerField()),
                ('cv', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cartype')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.fueltype')),
                ('gearbox_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.gearboxtype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.location')),
            ],
        ),
    ]
